###########
#  site.title, site.url, site.path

title: 'The World Factbook'

## note: in path do NOT include root (trailing slash) e.g. (/) - use empty string instead
path:  '/factbook'
url:   'http://openmundi.github.io/factbook'


##  all world factbook regions
regions:
- Europe
- South Asia
- Central Asia
- East & Southeast Asia
- Middle East
- Africa
- North America
- Central America and Caribbean
- South America
- Australia-Oceania
- Antarctica
- Oceans
- World         ## note: official assigned world region is oceans



########
# more settings

markdown: kramdown

collections:
  profiles:
    output: true


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
